### ISSUE TITLE
wget not found

### ISSUE THREAD

**Issue by isghj5** [ethteck/decomp-jenkins#1]
My docker image didn't have wget installed default, so it fails on creation.

![wget not found](https://user-images.githubusercontent.com/42048411/128618129-4e3070bb-87d6-4a96-9333-6ad9bce6ee08.png)

I added wget to the apt-get command on line 20 to get it working.

**Comment by ethteck** [comment]
Huh! I wonder why this worked for us.. Maybe an upstream image changed. Thanks :)

**Comment by ethteck** [comment]
Oh, could you open a PR with the change?
